## python for Machine learning

# Numpy

In [1]:
import numpy as np

In [2]:
# single dimensional array
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [3]:
# multi dimensional array 
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [4]:
type(n1)

numpy.ndarray

In [5]:
type(n2)

numpy.ndarray

In [6]:
n_zeros=np.zeros((1,2))
n_zeros

array([[0., 0.]])

In [7]:
n_zeros=np.zeros((5,5))
n_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
n_full=np.full((2,2),10)

In [9]:
n_full

array([[10, 10],
       [10, 10]])

In [10]:
n_arange=np.arange(10,20)
n_arange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
n_arange=np.arange(10,50,5)
n_arange

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
n_arange=np.arange(2,22,2)
n_arange

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [13]:
n_random=np.random.randint(1,100,5)
n_random

array([33,  1,  1, 71, 75])

In [14]:

n1=np.array([[1,2,3,4],[4,3,2,1]])
n1

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [15]:
#checking the shape of numpy array
n1.shape=(4,2)

In [16]:
n1

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [17]:
n1.shape=(8,1)
n1

array([[1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1]])

In [18]:
n1=np.array([10,20,30])


In [19]:
n2=np.array([40,50,60])

In [20]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [22]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

## numpy intersection & difference

In [23]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])

In [24]:
# common elelment 
np.intersect1d(n1,n2)

array([50, 60])

In [25]:
# n1-n2 
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [26]:
# n2-n1
np.setdiff1d(n2,n1)


array([70, 80, 90])

## Addition of Numpy Array

In [27]:
n1=np.array([10,20])
n1

array([10, 20])

In [28]:
n2=np.array([30,40])
n2

array([30, 40])

In [29]:
np.sum([n1,n2])

100

In [30]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [31]:
np.sum([n1,n2], axis=1)

array([30, 70])

## Scalar calculation 

In [32]:
n1

array([10, 20])

In [33]:
n1=n1+1
n1

array([11, 21])

In [34]:
n1=n1-1
n1

array([10, 20])

In [35]:
n1=n1*2
n1

array([20, 40])

In [36]:
n1=n1/2
n1

array([10., 20.])

## Numpy fucntion 

In [37]:
np.mean(n1)

15.0

In [38]:
np.std(n1)

5.0

In [39]:
np.median(n1)

15.0

In [40]:
# Saving Numpy Array
np.save('my_numpy',n1)


In [41]:
# Loading Numpy Array
np.load('my_numpy.npy')

array([10., 20.])